name: CPILint Analysis

on:
  workflow_dispatch:

env:
  CPILINT_VERSION: "1.1.0"

jobs:
  cpilint-analysis:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Download artifact from previous workflow
      - name: Download iFlow ZIPs
        uses: actions/download-artifact@v4
        with:
          name: downloaded-iflows
          path: downloads

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Download CPILint
        shell: powershell
        run: |
          $version = "${env:CPILINT_VERSION}"
          $url = "https://github.com/mwittrock/cpilint/releases/download/v$version/cpilint-$version.zip"

          New-Item -ItemType Directory -Force -Path cpilint | Out-Null

          Invoke-WebRequest `
            -Uri $url `
            -OutFile cpilint.zip

          Expand-Archive `
            -Path cpilint.zip `
            -DestinationPath cpilint `
            -Force

          Write-Host "CPILint installed"

      - name: Extract iFlow ZIPs
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path temp_iflows | Out-Null

          $zips = Get-ChildItem downloads -Filter *.zip

          if ($zips.Count -eq 0) {
            Write-Host "No ZIP files found."
            exit 0
          }

          foreach ($zip in $zips) {
            $target = Join-Path "temp_iflows" $zip.BaseName

            New-Item -ItemType Directory -Force -Path $target | Out-Null

            Expand-Archive `
              -LiteralPath $zip.FullName `
              -DestinationPath $target `
              -Force
          }

      - name: Run CPILint Analysis
        shell: powershell
        run: |
          $cpilintRoot = Get-ChildItem cpilint -Directory | Select-Object -First 1
          $cpilintDir = $cpilintRoot.FullName

          $classpath = "$cpilintDir\lib\*;$cpilintDir\logback"
          $rulesFile = "$cpilintDir\samples\naming.xml"

          New-Item -ItemType Directory -Force -Path cpilint-results | Out-Null

          $iflowDirs = Get-ChildItem temp_iflows -Directory

          foreach ($dir in $iflowDirs) {

            $iflowName = $dir.Name

            Write-Host "Analyzing $iflowName"

            $cmd = "java -classpath `"$classpath`" org.cpilint.CliClient -rules `"$rulesFile`" -unpacked-files `"$($dir.FullName)`" -boring"

            $output = cmd /c $cmd 2>&1

            $resultFile = "cpilint-results\$iflowName-result.txt"

            $output | Out-File `
              -FilePath $resultFile `
              -Encoding utf8

            Write-Host $output
          }

      - name: Upload CPILint Results
        uses: actions/upload-artifact@v4
        with:
          name: cpilint-results
          path: cpilint-results
