trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true
  fetchDepth: 0

- script: |
    VERSION=8.28.0

    wget -q \
      https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz

    tar -xzf gitleaks_${VERSION}_linux_x64.tar.gz

    chmod +x gitleaks
    sudo mv gitleaks /usr/local/bin

    gitleaks version
  displayName: Install Gitleaks

- script: |
    gitleaks git \
      --log-opts="-2" \
      --report-format json \
      --report-path gitleaks-report.json \
      --verbose
  displayName: Run Gitleaks (Latest Commit Only)
