name: Postman Validation for iFlows

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IFLOW_BRANCH: feature
  IFLOW_DIRECTORY: btp-iflows
  POSTMAN_DIRECTORY: postman

jobs:
  postman-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4

      - name: Checkout iFlow Feature Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.IFLOW_BRANCH }}
          path: iflows

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-junitfull

      - name: Create Reports Folder
        run: mkdir -p reports

      - name: Execute Postman Collections
        env:
          CPI_HOST: ${{ secrets.CPI_HOST }}
          CPI_USERNAME: ${{ secrets.CPI_USERNAME }}
          CPI_PASSWORD: ${{ secrets.CPI_PASSWORD }}
        run: |

          COLLECTION_DIR="iflows/${POSTMAN_DIRECTORY}"

          if [ ! -d "$COLLECTION_DIR" ]; then
            echo "No Postman directory found."
            exit 1
          fi

          for collection in "$COLLECTION_DIR"/*.postman_collection.json
          do
            if [ ! -f "$collection" ]; then
              echo "No Postman collections found."
              exit 1
            fi

            NAME=$(basename "$collection" .postman_collection.json)

            echo "==================================="
            echo "Running collection: $NAME"
            echo "==================================="

            newman run "$collection" \
              --env-var host="$CPI_HOST" \
              --env-var username="$CPI_USERNAME" \
              --env-var password="$CPI_PASSWORD" \
              -r cli,junitfull \
              --reporter-junitfull-export "reports/${NAME}.xml"

          done

      - name: Upload Newman Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results
          path: reports
