name: Postman Validation for iFlows

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IFLOW_BRANCH: feature
  IFLOW_DIRECTORY: btp-iflows
  POSTMAN_DIRECTORY: postman

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-junitfull

      - name: Create Reports Folder
        run: mkdir -p reports

      - name: Run All Postman Collections
        run: |
          shopt -s nullglob

          for collection in ${POSTMAN_DIRECTORY}/*.postman_collection.json
          do
            name=$(basename "$collection" .postman_collection.json)

            echo "Running $name"

            newman run "$collection" \
              -r cli,junitfull \
              --reporter-junitfull-export reports/${name}.xml
          done

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: reports
